### ISSUE TITLE
Error ;-;

### ISSUE THREAD

**Issue by iSnowuwu** [OhTheDungeon/OhTheDungeon#13]
I have try to fix this error without luck
So i hope someone can help me
error:
Could not load 'plugins\OhTheDungeon.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:147) ~[server.jar:3124-Bukkit-384e116]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:393) ~[server.jar:3124-Bukkit-384e116]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[server.jar:3124-Bukkit-384e116]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:382) ~[server.jar:3124-Bukkit-384e116]
at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:226) ~[server.jar:3124-Bukkit-384e116]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:963) ~[server.jar:3124-Bukkit-384e116]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:297) ~[server.jar:3124-Bukkit-384e116]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
at otd.Main.<init>(Main.java:125) ~[?:?]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350) ~[?:?]
at java.lang.Class.newInstance(Class.java:642) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[server.jar:3124-Bukkit-384e116]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:143) ~[server.jar:3124-Bukkit-384e116]
... 7 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.ChatColor
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142) ~[server.jar:3124-Bukkit-384e116]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[server.jar:3124-Bukkit-384e116]
at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
at otd.Main.<init>(Main.java:125) ~[?:?]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350) ~[?:?]
at java.lang.Class.newInstance(Class.java:642) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[server.jar:3124-Bukkit-384e116]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:143) ~[server.jar:3124-Bukkit-384e116]
... 7 more

**Comment by OhTheDungeon** [comment]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor

It already said quite clear. You need to use spigot or paper instead of CraftBukkit
