### ISSUE TITLE
Error starting v15.8 on Spigot 1.18.1

### ISSUE THREAD

**Issue by steve4744** [OhTheDungeon/OhTheDungeon#17]
Upgrading from 15.3 with an existing config setup I get this error, and the plugin is disabled.
```
[12:08:56] [Server thread/INFO]: [Oh_the_dungeons_youll_go] Enabling Oh_the_dungeons_youll_go v15.8
[12:08:56] [Server thread/ERROR]: Error occurred while enabling Oh_the_dungeons_youll_go v15.8 (Is it up to date?)
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 1 column 7917 path $.dict.
        at com.google.gson.Gson.fromJson(Gson.java:947) ~[gson-2.8.8.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.8.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.8.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:817) ~[gson-2.8.8.jar:?]
        at otd.config.WorldConfig.loadWorldConfig(WorldConfig.java:218) ~[?:?]
        at otd.Main.onEnable(Main.java:177) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:525) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:439) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:232) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 1 column 7917 path $.dict.
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.8.jar:?]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:504) ~[gson-2.8.8.jar:?]
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413) ~[gson-2.8.8.jar:?]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184) ~[gson-2.8.8.jar:?]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.8.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) ~[gson-2.8.8.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) ~[gson-2.8.8.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
        ... 14 more
```

**Comment by steve4744** [comment]
My bad - comparing world_config.yml files I was able to find a spurious comma in my original file.
