### ISSUE TITLE
Spigot 1.18.2

### ISSUE THREAD

**Issue by ErythroCraft** [OhTheDungeon/OhTheDungeon#51]
* You SHOULD use **English** or **Chinese** in an issue report.
* Make sure you use the diagnostic tools first (under `/otd` -> `utils`)

**Version**
1. Server version: Spigot v1_18_R2
2. Plugin Version: 17_Rain Water_2022

**Describe the bug**
Could load OTD by using spigot 1.18.2

**To Reproduce**
Steps to reproduce the behavior: Updated server version to 1.18.2 r2

**Expected behavior**
A simple version update can fix it.

**Screenshots**
Not on this time.

**Comment by sphings79** [comment]
```
<html>
<body>
<!--StartFragment-->

[14:45:31] [Server thread/ERROR]: Could not load 'plugins\otd.jar' in folder 'plugins'
--
33 | org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedOperationException: Unknown server version...
34 | at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
35 | at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
36 | at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
37 | at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:417) ~[paper-1.18.2.jar:git-Paper-220]
38 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-220]
39 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.18.2.jar:git-Paper-220]
40 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-220]
41 | at java.lang.Thread.run(Thread.java:833) ~[?:?]
42 | Caused by: java.lang.UnsupportedOperationException: Unknown server version...
43 | at otd.Main.<init>(Main.java:170) ~[otd.jar:?]
44 | at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
45 | at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
46 | at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
47 | at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
48 | at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
49 | at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
50 | at java.lang.Class.newInstance(Class.java:645) ~[?:?]
51 | at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:83) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
52 | at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
53 | ... 7 more
54 | [14:45:31] [Server thread/ERROR]: [AngelChest] The included JeffLib version (n/a)does not fully support the Minecraft version you are currently running:

<!--EndFragment-->
</body>
</html>[14:45:31] [Server thread/ERROR]: Could not load 'plugins\otd.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedOperationException: Unknown server version...
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:417) ~[paper-1.18.2.jar:git-Paper-220]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-220]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.18.2.jar:git-Paper-220]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-220]
	at java.lang.Thread.run(Thread.java:8[33](https://mclo.gs/aqgLSNG#L33)) ~[?:?]
Caused by: java.lang.UnsupportedOperationException: Unknown server version...
	at otd.Main.<init>(Main.java:170) ~[otd.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:[34](https://mclo.gs/aqgLSNG#L34)7) ~[?:?]
	at java.lang.Class.newInstance(Class.java:6[45](https://mclo.gs/aqgLSNG#L45)) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:83) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:1[53](https://mclo.gs/aqgLSNG#L53)) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	... 7 more
[14:45:31] [Server thread/ERROR]: [AngelChest] The included JeffLib version (n/a)does not fully support the Minecraft version you are currently running:
```
