### ISSUE TITLE
請求更新支援 MythicMobs 5.0

### ISSUE THREAD

**Issue by h266579110** [OhTheDungeon/OhTheDungeon#55]
* You SHOULD use **English** or **Chinese** in an issue report.
* Make sure you use the diagnostic tools first (under `/otd` -> `utils`)

**Version**
Paper 1.18.2 -264
Oh_the_dungeons_youll_go v17_Insects_Awaken_2022_P1

**Describe the bug**
```
[23:48:53 ERROR]: Could not pass event SpawnerSpawnEvent to Oh_the_dungeons_youll_go v17_Insects_Awaken_2022_P1
java.lang.NoClassDefFoundError: io/lumine/xikage/mythicmobs/MythicMobs
        at otd.integration.MythicMobsImpl$MythicMobsOTDImpl.getMobNames(MythicMobsImpl.java:96) ~[otd.jar:?]
        at otd.integration.MythicMobsImpl.spawnSmallBoss(MythicMobsImpl.java:70) ~[otd.jar:?]
        at otd.listener.SpawnerListener.spawnerNormalLogic(SpawnerListener.java:241) ~[otd.jar:?]
        at otd.listener.SpawnerListener.onSpawner(SpawnerListener.java:336) ~[otd.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor106.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-264]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callSpawnerSpawnEvent(CraftEventFactory.java:1688) ~[paper-1.18.2.jar:git-Paper-264]
        at net.minecraft.world.level.BaseSpawner.serverTick(BaseSpawner.java:186) ~[?:?]
        at net.minecraft.world.level.block.entity.SpawnerBlockEntity.serverTick(SpawnerBlockEntity.java:54) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1207) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1159) ~[?:?]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:917) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:682) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1591) ~[paper-1.18.2.jar:git-Paper-264]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-264]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-264]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-264]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-264]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.lumine.xikage.mythicmobs.MythicMobs
        ... 22 more
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by OhTheDungeon** [comment]
`17_Spring_Equinox_2022`
