### ISSUE TITLE
On boot: '"otd.config.WorldConfig.db" is null'. Started after update to spring equinox and 1.18.2 (paper)

### ISSUE THREAD

**Issue by BigScary** [OhTheDungeon/OhTheDungeon#57]
* You SHOULD use **English** or **Chinese** in an issue report.
* Make sure you use the diagnostic tools first (under `/otd` -> `utils`)

**Version**
1. Spigot/Paper Version:
**This server is running Paper version git-Paper-249 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: c8e49cc)**
3. Plugin Version
**v17_Spring_Equinox_2022**
(Remember, `latest` is not a valid version)

**Describe the bug**
No commands work, including the utils commands. Dungeons are not spawning. This started after updating the server to 1.18.2 and to the spring equinox plugin version. Before that, all was well. See below error from boot logs:

[09:01:05] [Server thread/INFO]: [Oh_the_dungeons_youll_go] Enabling Oh_the_dungeons_youll_go v17_Spring_Equinox_2022
[09:01:05] [Server thread/ERROR]: Error occurred while enabling Oh_the_dungeons_youll_go v17_Spring_Equinox_2022 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "otd.config.storage.ConfigImpl.setValue(String, String)" because "otd.config.WorldConfig.db" is null
	at otd.config.WorldConfig.actualSave(WorldConfig.java:242) ~[otd.jar:?]
	at otd.config.WorldConfig.update(WorldConfig.java:498) ~[otd.jar:?]
	at otd.config.WorldConfig.loadWorldConfigUpdate(WorldConfig.java:350) ~[otd.jar:?]
	at otd.config.WorldConfig.loadWorldConfig(WorldConfig.java:288) ~[otd.jar:?]
	at otd.Main.onEnable(Main.java:216) ~[otd.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-249]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-249]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:289) ~[paper-1.18.2.jar:git-Paper-249]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-249]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-249]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:01:05] [Server thread/INFO]: [Oh_the_dungeons_youll_go] Disabling Oh_the_dungeons_youll_go v17_Spring_Equinox_2022
[09:01:05] [Server thread/ERROR]: Error occurred while disabling Oh_the_dungeons_youll_go v17_Spring_Equinox_2022 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "otd.config.storage.ConfigImpl.close()" because "otd.config.WorldConfig.db" is null
	at otd.config.WorldConfig.close(WorldConfig.java:502) ~[otd.jar:?]
	at otd.Main.onDisable(Main.java:184) ~[otd.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-249]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-249]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:289) ~[paper-1.18.2.jar:git-Paper-249]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-249]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-249]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by OhTheDungeon** [comment]
Your config is broken. Backup and remove the `plugins\Oh_the_dungeons_youll_go` directory.

**Comment by BigScary** [comment]
Your suggested solution is throw away loot customizations that took a week to put together?

**Comment by OhTheDungeon** [comment]
1. This plugin doesn't use `world_config.json` since version 15.13
2. This mod will automatically update the config version for you, unless you manually changed the config and breaks the signatures

**Comment by OhTheDungeon** [comment]
Also we provides a `backup` utils to import & export the config. You can try: 

1. Backup-Export in old version
2. Copy the backup from `backup` folder
3. Update to new version and remove the plugin directory
4. Copy back the `backup` folder and import it in the GUI

**Comment by BigScary** [comment]
Thanks for getting back to me. I'm failing to find a command, Backup-Export, mentioned above? I also checked the docs you have here on GitHub. If it's not a command and you're referring to something in the in-game control panel (/otd_cp command), that fails to open for me due to the issue I described above. Is there any workaround?

**Comment by OhTheDungeon** [comment]
Please check each item in the GUI carefully
under `/otd` -> `utils`

15.13 will automatically update the config for you, so no longer need for backup

**Comment by BigScary** [comment]
> Please check each item in the GUI carefully

That command does not work for me, I get "null" in the console. I assume the command is not working for the same reason I get the error during boot. Is there another way to generate this backup I need?

**Comment by OhTheDungeon** [comment]
I just found that you are using a old version.
Please test on `17_Spring_Equinox_2022_P1` first, I test with it and didn't get any error, the config could properly generate.

**Comment by BigScary** [comment]
Yep, re-generating the config.db with latest version worked. Thank you for giving me enough information to guess the workaround.
