### ISSUE TITLE
Could not pass event to SpawnerSpawnEvent .... null

### ISSUE THREAD

**Issue by skruis** [OhTheDungeon/OhTheDungeon#72]
**Version**
1. Spigot/Paper Version: 3528-Spigot-56be6a8-031eaad (MC: 1.19)
2. Plugin Version - V19_Grain_in_Ear

**Describe the bug**
Error is logged frequently in dungeons. 

`[Server thread/ERROR]: Could not pass event SpawnerSpawnEvent to Oh_the_dungeons_youll_go v19_Grain_in_Ear
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:575) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callSpawnerSpawnEvent(CraftEventFactory.java:1507) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.world.level.MobSpawnerAbstract.a(MobSpawnerAbstract.java:158) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.world.level.block.entity.TileEntityMobSpawner.b(SourceFile:54) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.world.level.chunk.Chunk$a.a(Chunk.java:889) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.world.level.chunk.Chunk$d.a(Chunk.java:841) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.world.level.World.O(World.java:645) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:430) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1290) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:394) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1010) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3528-Spigot-56be6a8-031eaad]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'boolean org.bukkit.persistence.PersistentDataContainer.has(org.bukkit.NamespacedKey)'
	at otd.script.listener.DungeonEventListener.onSpawner(DungeonEventListener.java:177) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor77.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	... 16 more`

**To Reproduce**
Start a world, generate a roguelike dungeon, walk around.

**Comment by OhTheDungeon** [comment]
* Make sure you use the diagnostic tools first (under `/otd` -> `utils`)

Like what it said, use paper instead of spigot. This is a known bug for current spigot
